-- Run this in your Supabase SQL Editor

create table questions (
  id bigint generated by default as identity primary key,
  text text not null,
  options jsonb not null,
  correct_answer int not null,
  time_limit int default 20,
  created_at timestamp with time zone default timezone('utc', now())
);

create table scores (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score int not null,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Optional: Enable RLS and policies if needed, but for now we assume public or authenticated client.
-- If you use the Anon key, you might need to Enable RLS and add "True" policies for MVP.
alter table questions enable row level security;
create policy "Enable all access for all users" on questions for all using (true) with check (true);

alter table scores enable row level security;
create policy "Enable all access for all users" on scores for all using (true) with check (true);
